"""add section schedules

Revision ID: a4ed3bca1600
Revises: 651c090304af
Create Date: 2026-09-05 20:11:02.980995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ed3bca1600'
down_revision: Union[str, Sequence[str], None] = '651c090304af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_schedules')
    # ### end Alembic commands ###
