"""create digital verification tables

Revision ID: d902e479da28
Revises: 05093f028055
Create Date: 2026-09-06 10:27:39.158376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd902e479da28'
down_revision: Union[str, Sequence[str], None] = '05093f028055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('certificate_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('verification_code', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('transcript_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('verification_code', sa.String(length=150), nullable=False),
    sa.Column('transcript_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_table('digital_stamps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=True),
    sa.Column('transcript_verification_id', sa.UUID(), nullable=True),
    sa.Column('stamp_code', sa.String(length=150), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stamp_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['transcript_verification_id'], ['transcript_verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stamp_code')
    )
    op.create_table('qr_verification_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=True),
    sa.Column('transcript_verification_id', sa.UUID(), nullable=True),
    sa.Column('verification_url', sa.String(length=1000), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['transcript_verification_id'], ['transcript_verifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_verification_metadata')
    op.drop_table('digital_stamps')
    op.drop_table('transcript_verifications')
    op.drop_table('certificates')
    # ### end Alembic commands ###
